### ISSUE TITLE
Hold restaurant data as .json, interpolate into page

### ISSUE THREAD

**Issue by LoneRifle** [farrahfazirah/eatcb#1]
Hello,

I'm interested in making ongoing improvements to eatcb via contributing PRs. My intent is to fork the library and make a series of changes that, hopefully over time, would allow eatcb to:
 - pack more restaurant entries without winding up with a gigantic index.html file, and;
 - introduce some form of search (current idea is for simple postcode lookup)

Assuming that I manage to spare the time to do this, I will start by refactoring index.html such that the restaurant entries are extracted into a .json. On load, the browser will fetch this .json and convert the entries therein to the cards that we have now

Let me know what you think!

**Comment by farrahfazirah** [comment]
Hi @LoneRifle, 

Yeah, that would be awesome! I'm a UI/UX designer with some front-end dev knowledge so your help as a full-stack dev would be super great. I've given you access as collaborator.

Let's keep in touch.
